name: waitwhat-infra
runtime:
  name: nodejs
  options:
    typescript: true
description: Cloudflare infrastructure for WaitWhat lecture platform
config:
  pulumi:tags:
    value:
      pulumi:template: typescript
